targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dartdevc
      # Optional: if you have issues with specific folders, you can exclude them.
      # For example, to exclude the .git directory:
      # build_web_compilers|entrypoint:
      #   exclude:
      #     - .git/**