// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVchAgiaHCrxaNnyJRR4C6hoF7ThTyW1Y',
    appId: '1:1030587373633:web:8c9e32dc73bd9282840ec0',
    messagingSenderId: '1030587373633',
    projectId: 'letdem-d28a8',
    authDomain: 'letdem-d28a8.firebaseapp.com',
    storageBucket: 'letdem-d28a8.firebasestorage.app',
    measurementId: 'G-W4RJGGKC5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYZClEaZy1KGNlkOXwwHobYc5AXxVv9Cs',
    appId: '1:1030587373633:android:b1f75a37e2bd6e37840ec0',
    messagingSenderId: '1030587373633',
    projectId: 'letdem-d28a8',
    storageBucket: 'letdem-d28a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8vc6hqXwSOm393MdvOuG_TRI9rmIwcsg',
    appId: '1:1030587373633:ios:8e5bc6296facc018840ec0',
    messagingSenderId: '1030587373633',
    projectId: 'letdem-d28a8',
    storageBucket: 'letdem-d28a8.firebasestorage.app',
    iosBundleId: 'com.letdem.letdemapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8vc6hqXwSOm393MdvOuG_TRI9rmIwcsg',
    appId: '1:1030587373633:ios:3ed93ceee79922da840ec0',
    messagingSenderId: '1030587373633',
    projectId: 'letdem-d28a8',
    storageBucket: 'letdem-d28a8.firebasestorage.app',
    iosBundleId: 'com.example.letdem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVchAgiaHCrxaNnyJRR4C6hoF7ThTyW1Y',
    appId: '1:1030587373633:web:9486e1bfa1a315ac840ec0',
    messagingSenderId: '1030587373633',
    projectId: 'letdem-d28a8',
    authDomain: 'letdem-d28a8.firebaseapp.com',
    storageBucket: 'letdem-d28a8.firebasestorage.app',
    measurementId: 'G-75F0J281VB',
  );
}
